apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  resources:
  - name: git-repo
    type: git
  - name: image
    type: image
  workspaces:
  - name: pipeline-workspace
  tasks:
  - name: cleanup-folder
    taskRef:
      name: cleanup-folder-task
    params:
    - name: path
      value: ".git"
    workspaces:
    - name: pipeline
      workspace: pipeline-workspace
  - name: maven-build
    taskRef:
      name: mvn-task
    resources:
      inputs:
      - name: source
        resource: git-repo
    workspaces:
    - name: maven-repo
      workspace: pipeline-workspace 
    params:
    - name: GOALS
      value: [clean, package]
    runAfter:
    - cleanup-folder
  - name: build-image
    taskRef:
      name: buildah-task
    resources:
      outputs:
      - name: image
        resource: image
    workspaces:
    - name: pipeline-workspace
      workspace: pipeline-workspace 
    params:
    - name: TLSVERIFY
      value: "false"
    runAfter:
    - maven-build
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: pipeline-workspace
      workspace: pipeline-workspace 
    runAfter:
    - build-image
#  - name: update-deployment
#   taskRef:
#     name: update-deployment
#   resources:
#     inputs:
#     - name: image
#       resource: image
#   params:
#   - name: deployment
#     value: $(params.deployment-name)
#   runAfter:
#   - apply-manifests
