apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: get-started-java-trigger-template
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generatedName: build-and-deploy-triggered-
    spec:
      pipelineRef:
        name: build-and-deploy
      resources:
      - name: git-repo
        resourceRef:
          name: app-repo
      - name: image
        resourceRef:
          name: app-image
      workspaces:
      - name: pipeline-workspace
        persistentVolumeClaim:
          claimName: tekton-workspace-pvc
