apiVersion: apps/v1
kind: Secret
apiVersion: v1
metadata:
  name: mongo-url
data:
  mongo-url: bW9uZ29kYjovL21vbmdvOm1vbmdvQG1vbmdvZGI6MjcwMTcvP2F1dGhTb3VyY2U9bXlkYg==
type: Opaque 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-started-java-deployment
  labels:
    app: get-started-java
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"get-started-java:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"get-started-java-container\")].image"}]
spec:
  selector:
    matchLabels:
      app: get-started-java
  template:
    metadata:
      labels:
        app: get-started-java
    spec:
      containers:
      - name: get-started-java-container
        image: get-started-java
        ports:
        - containerPort: 9080
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongo-url
                key: mongo-url   
---
apiVersion: v1
kind: Service
metadata:
  name: get-started-java-service
spec:
  selector:
    app: get-started-java
  ports:
  - protocol: TCP
    port: 9080
---    
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: get-started-java
spec:
  to:
    kind: Service
    name: get-started-java-service
  port:
    targetPort: 9080
 
    
